---
title: "Inflow model"
author: "KKH, from B"
format: html
editor: visual
---

This is to create the inflow models for each stream needed to make the one inflow for Sunapee.

```{r get the met data}

## historic met
NLDAS <- arrow::open_dataset(arrow::s3_bucket(paste0("bio230121-bucket01/flare/drivers/met/gefs-v12/stage3/site_id=",flow_site),
                                   endpoint_override = 'renc.osn.xsede.org',
                                   anonymous = TRUE)) |>
  filter(variable %in% c('precipitation_flux', "air_temperature", "relative_humidity", "surface_downwelling_shortwave_flux_in_air", "surface_downwelling_longwave_flux_in_air", "")) |> 
  collect() |> 
  reframe(.by = all_of(c("datetime", "variable")), mean_prediction = mean(prediction)) |> 
  pivot_wider(names_from = 'variable', values_from = 'mean_prediction') |> 
  rename(AirTemp = air_temperature, Rain = precipitation_flux)

flow_site = "sunp"

z <- arrow::open_dataset(noaa_df) |>
  filter(site_id == "ccre",
         reference_datetime == "2024-01-01"
         #variable %in% c("precipitation_flux", "surface_downwelling_shortwave_flux_in_air")
         ) |>
  collect()

#### bring in NLDAS-2 climate data ####
MetData <- read.csv('./NLDASData/NLDAS_Data_2019_2020/Sunapee_2018_12_31_2020_12_31_alldata.csv', header=T, na.strings=NA) 
MetData <- MetData %>%   
  select(local_dateTime, ShortWave.W_m2, LongWave.W_m2, AirTemp.C, RelHum, WindSpeed.m_s, Rain.m_day)
colnames(MetData) <- c("time", 'ShortWave', "LongWave", "AirTemp", "RelHum", "WindSpeed", "Rain")
```

```{r }
MetData <- MetData |> 
  
```
